// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiht9lZS5xStQZdBZwGaeHI3mqYnsMyP8',
    appId: '1:327485994364:web:74be1878d6e52b8a9f60f9',
    messagingSenderId: '327485994364',
    projectId: 'safehomeai-8119c',
    authDomain: 'safehomeai-8119c.firebaseapp.com',
    storageBucket: 'safehomeai-8119c.appspot.com',
    measurementId: 'G-59BVBVV2NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeoGdYB0piZ4SkOy4xByAh6P5QgMnNodw',
    appId: '1:327485994364:android:f2f47d8fb2e703499f60f9',
    messagingSenderId: '327485994364',
    projectId: 'safehomeai-8119c',
    storageBucket: 'safehomeai-8119c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDa4vQpPrb8wldpl-GmTdTPZIwrHTSG8',
    appId: '1:327485994364:ios:93a28596f84529709f60f9',
    messagingSenderId: '327485994364',
    projectId: 'safehomeai-8119c',
    storageBucket: 'safehomeai-8119c.appspot.com',
    iosBundleId: 'com.andrushka.rpc.rockPaperScissorsMobile',
  );
}
