name: rock_paper_scissors_mobile
description: Flatter part of rock_paper_scissors CNN project


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  #tflite_flutter_helper: ^0.3.1
  camera: ^0.10.4
  tflite_flutter_helper_plus: ^0.0.2
  image_picker: ^1.1.2
  awesome_dialog: ^3.2.1
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  phone_form_field: ^9.2.7
  shared_preferences: ^2.3.2
  # camera_android_camerax: ^0.6.8+3
  #image: ^4.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/model_val_acc_0.71.tflite
  uses-material-design: true

